name: "🐛 Bug report"
description: "Something not working the way it should be?"

title: "[Bug?]: "
labels: bug/needs-info

body:
  - type: textarea
    attributes:
      label: What's not working?
      description: >
        Describe the bug here.
        The more detail you provide, the better,
        but try to start with a summary to frame the issue.
      placeholder: >
        The dev server doesn't seem to be working.
        When I run `yarn rw dev`,
        the web side doesn't start and throws `TypeError: cli.isMultipleCompiler is not a function`.
        I was just following the tutorial when I ran into this,
        so nothing fancy going on here.


        I think this probably has to do with [webpack-cli](https://github.com/webpack/webpack-cli).
        I skimmed the issues on their repo and it looks like they just released a new version.
        If we bump the version Redwood is using, it may resolve this.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How do we reproduce the bug?
      description: >
        What commands do we need to run?
        What packages do we need to install?
        What does the `schema.prisma` need to look like?
        Again, the more detail, the better.


        While this field is optional,
        you're much more likely to get a timely response and fix from us if you provide one.
        Issues without them are much harder for us to debug.
      placeholder: |
        1. create a new redwood app
        2. start the dev server

        ```shell
        yarn create redwood-app redwood-app
        # ...
        cd redwood-app
        yarn rw dev
        # ...
        web | [webpack-cli] TypeError: cli.isMultipleCompiler is not a function
        ```
    validations:
        required: false

  - type: textarea
    attributes:
      label: What's your environment? (If it applies)
      render: shell
      description: |
        Run `yarn rw info` and paste the output here.
      placeholder: |
        System:
          OS: macOS 12.3.1
          Shell: 5.8 - /bin/zsh
        Binaries:
          Node: 16.15.1 - /private/var/folders/dt/yks4v5m53k114qxgz6jh4pgw0000gn/T/xfs-0cbbe6f7/node
          Yarn: 3.2.1 - /private/var/folders/dt/yks4v5m53k114qxgz6jh4pgw0000gn/T/xfs-0cbbe6f7/yarn
        Databases:
          SQLite: 3.37.0 - /usr/bin/sqlite3
        Browsers:
          Chrome: 102.0.5005.115
          Safari: 15.4
        npmPackages:
          @redwoodjs/core: 1.5.2 => 1.5.2
    validations:
        required: false

  - type: checkboxes
    attributes:
      label: Are you interested in working on this?
      description: >
        No pressure—this is totally optional!
        We just want to invite you to contribute to Redwood.
        If you choose to contribute, the core team will be there to help you the whole way.


        If this issue is triaged as being lower priority,
        your willing and ableness to work on this will land it faster than waiting for one of us to pick it up.
      options:
        - label: I'm interested in working on this
