name: "📖 Documentation"
description: "A catch-all template for issues about documentation"

title: "[Documentation]: "
labels: topic/docs

body:
  - type: markdown
    attributes:
      value: >
        > **Whoa, what is this?**

        >

        > This is an issue form, a new type of issue template.
        We're trying it out because we want...

        > 1. issues to be more structured, (specifically, bug reports)

        > 2. to be more upfront about our process—i.e., what happens after you open an issue (see the paragraph below)

        >

        > We want the process of opening an issue to be smooth for you as a contributor,
        so please do let us know what you think [over on the forums](https://community.redwoodjs.com/t/what-do-you-think-of-the-new-github-issue-forms/3463).


        Thanks for taking the time to open an issue!
        Here's a bit of background on what you can expect about the process:

        - Expect a response from us (the core team) within three to seven days.
          - Usually we'll respond sooner than that, but sometimes we have a lot on our plate. Thanks for your patience!
        - After you open this, the Redwood bot will assign a core team member to it. They'll triage it.
          - If they don't within three to seven days, the Redwood bot will ping them. You should feel free to ping them too!

  - type: textarea
    attributes:
      label: Summary and description
      description: >
        The body of the issue, just like a regular GitHub issue.
        The more detail you provide, the better,
        but try to start with a summary to frame the issue.
        See the placeholder below for an example.
      placeholder: >
        In #5658, we changed the link to edit a page in the docs to always point to the docs in `/docs` instead of `/docs/versioned_docs`.
        While this was the right move, it's still not exactly clear what that links points to.
        We should tweak the text to be a little more explicit about what version (i.e. Canary) that it'll take users to.


        The text could be "Edit the most recent version of this page", "Edit the latest version of this page" or "Edit the Canary version of this page"—something along those lines.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Are you interested in working on this? (If it applies)
      description: >
        No pressure—this is totally optional!
        We just want to invite you to contribute to Redwood.
        If you choose to contribute, the core team will be there to help you the whole way.


        In some cases, if this issue is triaged as being lower priority,
        your willing- and ableness to work on this will land it faster than waiting for a core team member to pick it up.
        But if this is critical, it'll of course be escalated.
      options:
        - label: I'm interested in working on this
