name: "⭐️ Feature request"
description: "Have an idea for a new feature?"

title: "[Feature request]: "

body:
  - type: textarea
    attributes:
      label: Summary and description
      description: >
        The body of the issue, just like a regular GitHub issue.
        The more detail you provide, the better,
        but try to start with a summary to frame the issue.


        Here's a few questions to guide your writing:

        - What is this feature about? The CLI? The web side? The api side? Both?
        - Why does Redwood need this feature? I.e., what's the problem you're running up against?
        - What would this feature's API look like?
      placeholder: >
        This feature request is about the generators.
        I'd like for them to support writing to arbitrary locations on the file system.
        (Within a Redwood project of course.)


        Right now, generators write to specific locations:
        components write to `web/src/components`, pages to `web/src/pages`, etc.
        Except for scaffolds, this isn't configurable.
        (And even scaffolds are only slightly configurable at that.)


        The reason this matters is Redwood projects are meant to scale,
        and as Redwood projects grow in size
        (which they do quickly since the generators write a lot of files—tests, stories, mocks, etc.),
        file organization becomes important fast.
        So while Redwood likes to be opinionated,
        I think this is an area where some discretion could be left to the user.


        So I suggest adding a new option to all generator CLI commands: `--path`.
        This option takes a file path, relative to `src`.
        Here's an example:


        ```shell
        yarn rw g component dialog --path ui
        ```


        This would write to the following location:


        ```shell

        web/src/ui/

        └── Dialog/
          ├── Dialog.js
          ├── Dialog.stories.js
          └── Dialog.test.js
        ```


        Thanks for reading!
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Are you interested in working on this? (If it applies)
      description: >
        No pressure—this is totally optional!
        We just want to invite you to contribute to Redwood.
        If you choose to contribute, the core team will be there to help you the whole way.


        If this issue is triaged as being lower priority,
        your willing and ableness to work on this will land it faster than waiting for a core team member to pick it up.
      options:
        - label: I'm interested in working on this
