name: "⭐️ Feature request"
description: "Have an idea for a new feature?"

title: "[Feature request]: "

body:
  - type: markdown
    attributes:
      value: >
        > **Whoa, what is this?**

        >

        > This is an issue form, a new type of issue template.
        We're trying it out because we want...

        > 1. issues to be more structured, (specifically, bug reports)

        > 2. to be more upfront about our process—i.e., what happens after you open an issue (see the paragraph below)

        >

        > We want the process of opening an issue to be smooth for you as a contributor,
        so please do let us know what you think [over on the forums](https://community.redwoodjs.com/t/what-do-you-think-of-the-new-github-issue-forms/3463).


        Thanks for taking the time to open an issue!
        Here's a bit of background on what you can expect about the process:

        - Expect a response from us (the core team) within three to seven days.
          - Usually we'll respond sooner than that, but sometimes we have a lot on our plate. Thanks for your patience!
        - After you open this, the Redwood bot will assign a core team member to it. They'll triage it.
          - If they don't within three to seven days, the Redwood bot will ping them. You should feel free to ping them too!

  - type: textarea
    attributes:
      label: Summary and description
      description: >
        The body of the issue, just like a regular GitHub issue.
        The more detail you provide, the better,
        but try to start with a summary to frame the issue.
        See the placeholder below for an example.

        Here's a few questions to guide your writing:

        - What is this feature about? The CLI? The web side? The api side? Both?
          - This'll help us figure out whether it's a minor feature request or a major one
        - Why does Redwood need this feature?
          - I.e., what's the problem you're running up against?
        - What would this feature's API look like?
          - For example, if it's a new CLI command, what options does it take?
      placeholder: >
        This feature request is about the generators.
        I'd like for them to support writing to arbitrary locations on the file system.
        (Within a Redwood project of course.)


        Right now, generators write to specific locations:
        components write to `web/src/components`, pages to `web/src/pages`, etc.
        Except for scaffolds, this isn't configurable.
        (And even scaffolds are only slightly configurable at that.)


        The reason this matters is Redwood projects are meant to scale,
        and as Redwood projects grow in size
        (which they do quickly since the generators write a lot of files—tests, stories, mocks, etc.),
        file organization becomes important fast.
        So while Redwood likes to be opinionated,
        I think this is an area where some discretion could be left to the user.


        So I suggest adding a new option to all generator CLI commands: `--path`.
        This option takes a file path, relative to `src`.
        Here's an example:


        ```shell
        yarn rw g component dialog --path ui
        ```


        This would write to the following location:


        ```shell

        web/src/ui/

        └── Dialog/
          ├── Dialog.js
          ├── Dialog.stories.js
          └── Dialog.test.js
        ```


        Thanks for reading!
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Are you interested in working on this? (If it applies)
      description: >
        No pressure—this is totally optional!
        We just want to invite you to contribute to Redwood.
        If you choose to contribute, the core team will be there to help you the whole way.


        In some cases, if this issue is triaged as being lower priority,
        your willing- and ableness to work on this will land it faster than waiting for a core team member to pick it up.
        But if this is critical, it'll of course be escalated.
      options:
        - label: I'm interested in working on this
