name: "⭐️ Feature request"
description: "Have an idea for a new feature?"

title: "[Feature request]: "

body:
  - type: textarea
    attributes:
      label: Summary and description
      description: >
        The body of the issue, just like a regular GitHub issue.
        The more detail you provide, the better,
        but try to start with a summary to frame the issue.


        Here's a few questions to guide your writing:

        - What is this feature about? The CLI? The web side? The api side? Both?
        - Why does Redwood need this feature? I.e., what's the problem you're running up against?
        - What would this feature's API look like?
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Are you interested in working on this? (If it applies)
      description: >
        No pressure—this is totally optional!
        We just want to invite you to contribute to Redwood.
        If you choose to contribute, the core team will be there to help you the whole way.


        If this issue is triaged as being lower priority,
        your willing and ableness to work on this will land it faster than waiting for a core team member to pick it up.
      options:
        - label: I'm interested in working on this
